# Generated by Django 2.0.6 on 2018-06-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bland',
            name='data',
        ),
        migrations.RemoveField(
            model_name='colorcategory',
            name='data',
        ),
        migrations.RemoveField(
            model_name='item',
            name='data',
        ),
        migrations.RemoveField(
            model_name='size',
            name='data',
        ),
        migrations.RemoveField(
            model_name='type',
            name='data',
        ),
    ]
