# Generated by Django 2.0.6 on 2018-06-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180625_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_tsa',
            field=models.BooleanField(default=True, verbose_name='TSAロック対応'),
        ),
    ]
