# Generated by Django 2.0.6 on 2018-06-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180625_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bland',
            options={'ordering': ['name'], 'verbose_name': 'ブランド', 'verbose_name_plural': 'ブランド'},
        ),
        migrations.AlterModelOptions(
            name='colorcategory',
            options={'ordering': ['name'], 'verbose_name': 'カラー分類', 'verbose_name_plural': 'カラー分類'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['bland__name', 'capacity', 'name'], 'verbose_name': 'アイテム', 'verbose_name_plural': 'アイテム'},
        ),
        migrations.AlterModelOptions(
            name='itemfeecoef',
            options={'ordering': ['item__bland__name', 'item__capacity', 'item__name', 'starting_point'], 'verbose_name': 'アイテム料金係数', 'verbose_name_plural': 'アイテム料金係数'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['item__bland__name', 'item__capacity', 'item__name', 'order'], 'verbose_name': 'アイテム画像', 'verbose_name_plural': 'アイテム画像'},
        ),
        migrations.AlterModelOptions(
            name='lineuser',
            options={'ordering': ['-created_at'], 'verbose_name': 'LINEユーザー', 'verbose_name_plural': 'LINEユーザー'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['min_days'], 'verbose_name': 'サイズ', 'verbose_name_plural': 'サイズ'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name'], 'verbose_name': 'タイプ', 'verbose_name_plural': 'タイプ'},
        ),
    ]
